# Generated by Django 3.0.2 on 2020-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('size', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
    ]
